using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain;

public enum CustomerSettingType
{
    alertdefaultemailbody,
    alertdelay,
    alertemailsubject,
    alerteventviewerid,
    alertnotificationenable,
    applicationmetricsurl,
    bitlytest,
    contactfrequencyflag,
    contactfrequencyvalue,
    contactsurveydistributionfrequency,
    contactunsubmsg,
    contactunsubmsgdir,
    contactupdatetest,
    Customer,
    customerdirectoryid,
    deletelastaccessdays,
    delimiter,
    distributionchannel,
    distributiondayslimit,
    distributiondetailurl,
    distributionuploadchunksize,
    domain,
    emailtest,
    embeddeddatasize,
    enablegoogletwofa,
    enablepurgedata,
    isapplicationmetricsenabled,
    isautosave,
    lastdistributiondetailid,
    maskingfields,
    NoofdaysbeforePurgingMiddlewareLog,
    onpremsyncdistributionchunksize,
    piidataencryption,
    purgedata,
    purgedownloadeddata,
    requestsize,
    serviceclientid,
    serviceclientsecret,
    serviceurl,
    smsdelay,
    smstest,
    subscriptionurl,
    taskids,
    twowaycommunication,
    uniqueidentifier,
    unsubidentity,
    unsubscribedcontactsurl,
    unsubscribedfailureurl,
    unsubscribedsuccessurl,
    updatecredenialsurl,
}
